version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: test_nginx
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    ports:
      - 80:80
      - 443:443
